twelvelabs-io/twelvelabs-python

- API.md
- twelvelabs/models/__init__.py
- twelvelabs/models/_base.py
- twelvelabs/models/generate.py
- twelvelabs/models/index.py
- twelvelabs/models/search.py
- twelvelabs/models/task.py
- twelvelabs/models/video.py
- twelvelabs/resources/engine.py
- twelvelabs/resources/index.py
- twelvelabs/resources/task.py
- twelvelabs/resources/video.py
Before this change, an API such as `client.index.video.logo()` returned a list of Pydantic objects. While each element of the list supported `BaseModel` methods such as `model_dump_json()`, the list itself did not, making it awkward to serialize the returned data.
This change introduces a new generic type, `RootModelList`, that subclasses `RootModel[List[T]]`, which in turn subclasses `BaseModel`. In addition, `RootModelList` implements the methods `__init__`, `__iter__`, `__getitem__` and `__len__`, providing access to its `root` member variable, allowing the wrapper object to be used in place of a list and minimizing changes to existing code.
Relevant method signatures evolve in a natural way, from returning `List[models.SomeType]` to `RootModelList[models.SomeType]`; for example, …
> Created RootModelList so that lists returned from the APIs can be serialized

- .bumpversion.cfg
- .github/workflows/bump.yml
- .github/workflows/publish.yml
Added git workflows to leverage CI/CD pipeline.
> Add CI/CD workflows

- .github/workflows/bump.yml
Fixed bump order; git config first
> fix: bump order

- .github/workflows/bump.yml
under conducting test for workflow
> Test bump workflow

- .github/workflows/bump.yml
> fix: bump workflow

- examples/classify.py
- examples/generate.py
- examples/search.py
- examples/task.py
- examples/video.py
- twelvelabs/client.py
- twelvelabs/models/__init__.py
- twelvelabs/models/_base.py
- twelvelabs/models/classify.py
- twelvelabs/models/search.py
- twelvelabs/resources/__init__.py
- twelvelabs/resources/classify.py
- twelvelabs/resources/task.py
> Add classify apis

- examples/embed.py
- twelvelabs/client.py
- twelvelabs/models/__init__.py
- twelvelabs/models/embed.py
- twelvelabs/models/task.py
- twelvelabs/resources/__init__.py
- twelvelabs/resources/embed.py
Added Embed APIs. Please refer to these docs:
- [text embeddings](https://docs.twelvelabs.io/reference/text-embeddings)
- [video embeddings](https://docs.twelvelabs.io/reference/video-embeddings)
> Add Embed APIs

- twelvelabs/resources/embed.py
- twelvelabs/resources/task.py
Add dummy file field if "files" not assigned. This ensures request will be handled as multipart-form.
> fix: ensure multipart-form request

- twelvelabs/resources/embed.py
Renamed `scopes` to `video_embedding_scopes` in single create method to keep the params consistent.
> feat: rename `scopes` to `video_embedding_scopes`

- examples/classify.py
- twelvelabs/models/__init__.py
- twelvelabs/models/classify.py
- twelvelabs/resources/classify.py
Support pagination-model `ClassifyPageResult` with /classify/videos response instead of `ClassifyResult`
> feat: support pagination for /classify/videos

- twelvelabs/resources/search.py
Temporarily remove the warning message as it is not relevant with the current API version.
> fix: rollback warning message for search api

- twelvelabs/models/classify.py
Relocated `detailed_scores` field into `ClassifyClass`.
> Relocate `detailed_scores` into `ClassifyClass`

- README.md
Update the README file for the Image-to-video search feature.
> Update the README file for the Image-to-video search feature.

- README.md
Update the Prerequisites section
- [X ] Documentation update
- [X ] I have ensured my PR title is descriptive and in imperative mood.
- [X ] I have added necessary documentation (if appropriate).
> Remove "For consistent search results, Twelve Labs recommends you upload 360p videos."

- README.md
- examples/engine.py
- examples/index.py
- twelvelabs/resources/index.py
Updated model names (marengo2.5 -> marengo2.6 and pegasus1 -> pegasus1.1)
> feat: update model names

- README.md
Increase video duration to 30 minutes
> Pegasus: Increase video duration to 30 minutes

- twelvelabs/models/video.py
Added `source` in Video object
> feat: add `source` in Video object

- README.md
Update the link to the Dashboard page.
- [] New feature (non-breaking change which adds functionality)
> Update the link to the Dashboard page.

- README.md
Retrieve your API key: Improve clarity
> Retrieve your API key: Improve clarity

- requirements.txt
In a same virtual python env, users can not use multiple libraries that contains different version of pkg requirements.
currently we made versions specific like `pydantic == 2.4.2`, it's better to use `>=` to ensure the compatibility.
> chore: modify requirements.txt not specific

- twelvelabs/models/generate.py
- twelvelabs/models/index.py
> fix: inconsistent models

- README.md
> Update minimum resolution

- .gitignore
- twelvelabs/models/video.py
- twelvelabs/resources/video.py
Fixed some imports in video model
> fix: pydantic error in video model

- twelvelabs/models/video.py
fixed `embedding` type in `video` model
> fix: video.embedding field type

- README.md
- examples/index.py
- twelvelabs/types/index.py
supports pegasus-1.2 in create-index input, and updated example code and README
> feat: support pegasus1.2

- API.md
- examples/generate.py
- twelvelabs/models/__init__.py
- twelvelabs/models/generate.py
- twelvelabs/models/video.py
- twelvelabs/resources/generate.py
> feat: re-support gist api

- twelvelabs/types/index.py
Disallow pegasus1.1 option from IndexModel
> chore: sunset pegasus1.1

- examples/task.py
- twelvelabs/models/index.py
- twelvelabs/models/video.py
- twelvelabs/resources/task.py
- twelvelabs/resources/video.py
Removed support for `language` and `indexed_at`
> Remove support for language and indexed_at

- twelvelabs/models/generate.py
added two missing fields - `usage` and `highlight_summary`
API Docs: https://docs.twelvelabs.io/reference/summarize
> Missing fields on generate

- API.md
- README.md
- examples/generate.py
- twelvelabs/client.py
- twelvelabs/resources/generate.py
Serve /analyze endpoint as `analyze` and `analyze_stream` method, and added deprecation comment
> feat: support analyze api

- README.md
> Characters -> tokens

- .fernignore
add temporal readme to fernignore
> chore: fernignore includes beta readme
